server:
  port: 8123
  servlet:
    context-path: /api
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/scai_official_website?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
mybatis-plus:
  configuration:
    # 仅在本地环境打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 文件上传路径
local:
  path: /Users/lichengxiang/Documents/Coding/JavaCode/SCAI/SCAI-OfficialWebsite/Picture